Make SERVFAIL respond with SERVFAIL
cloudfoundry/dns-release pull request #87
Opened 2022-08-03 09:01 UTC by fearoffish

If an upstream nameserver responds with SERVFAIL, then bosh-dns should respond with SERVFAIL.

What does this solve? One of our customers was using a domain, which had/has a fault that returned SERVFAIL...however, currently bosh-dns switches all non network errors to be an NXDOMAIN error. This meant our customers application was receiving an incorrect DNS response. By adding this code we are able to pass the SERVFAIL back to the customer correctly.

[duplicate PR because committer email was wrong]

2022-08-03 11:41 UTC, friegger commented
Is related to https://github.com/cloudfoundry/bosh-dns-release/issues/74#issuecomment-742435974 which mentions the commit that introduced that behavior. With the standard configuration where bosh-dns would add other nameserver entries in resolv.conf to the list of recursors this will lead to the same nameserver being asked twice. Which is totally ok for our scenario, but might be relevant for others. The important part is that want the client to get the original error and not hide it behind a non-error response, so that the client can try again.

2022-08-15 15:23 UTC, lnguyen approved these changes
LGTM

2022-08-15 15:23 UTC, lnguyen commented
Can you rebase @fearoffish ?

2022-08-16 08:24 UTC, fearoffish commented
All good!

2022-08-18 14:29 UTC, rkoster requested changes

2022-08-18 14:29 UTC, rkoster commented on src/bosh-dns/dns/server/handlers/forward_handler.go
> +		if strings.Contains(err.Error(), "received SERVFAIL") {
would it be possible to get the status out of the dns.Msg? The current implementation feels a bit brittle. 

Found: https://pkg.go.dev/github.com/miekg/dns#MsgHdr.String

2022-08-18 16:17 UTC, fearoffish commented
Not without a bunch of other changes on how errors handled. This function only receives a message or a net error object.

2022-08-19 13:43 UTC, fearoffish commented on src/bosh-dns/dns/server/handlers/forward_handler.go
> +		if strings.Contains(err.Error(), "received SERVFAIL") {
Thanks for the pairing session. Changes pushed, tests still passing. yay!

2022-08-19 13:43 UTC, fearoffish commented
Changes pushed using error types instead of parsing strings. Much nicer.

2022-08-19 14:03 UTC, rkoster approved these changes

2022-08-19 14:03 UTC, merged

2022-08-19 14:03 UTC, rkoster commented
Thanks! @fearoffish